/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Beneficiary {
  'id' : string,
  'documents' : { 'id' : string, 'blob' : ExternalBlob },
  'name' : string,
  'helpHistory' : Array<string>,
  'helpType' : string,
  'address' : string,
  'contactDetails' : string,
}
export interface Birthday { 'day' : number, 'month' : number, 'year' : number }
export interface Campaign {
  'id' : string,
  'status' : string,
  'title' : string,
  'goalAmount' : bigint,
  'endDate' : string,
  'description' : string,
  'amountRaised' : bigint,
  'startDate' : string,
}
export interface Certificate {
  'id' : string,
  'issueDate' : string,
  'templateId' : string,
  'recipientName' : string,
  'certificateType' : string,
  'qrCode' : string,
}
export interface Donation {
  'id' : string,
  'memberId' : [] | [string],
  'date' : string,
  'donorName' : string,
  'campaignId' : [] | [string],
  'paymentMode' : string,
  'amount' : bigint,
  'receiptNumber' : string,
  'transactionId' : string,
}
export interface Enquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : string,
  'replied' : boolean,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Member {
  'id' : string,
  'dob' : Birthday,
  'status' : Status,
  'name' : string,
  'designation' : string,
  'joiningDate' : string,
  'email' : string,
  'referralId' : string,
  'address' : string,
  'gender' : Gender,
  'phone' : string,
  'photo' : ExternalBlob,
}
export interface Referral {
  'referredId' : string,
  'referrerId' : string,
  'timestamp' : string,
  'successful' : boolean,
}
export type Status = { 'active' : null } |
  { 'blocked' : null } |
  { 'deactivated' : null };
export interface UserProfile {
  'memberId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBeneficiary' : ActorMethod<[Beneficiary], undefined>,
  'addMemberReferral' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockMember' : ActorMethod<[string], undefined>,
  'createCertificate' : ActorMethod<[Certificate], undefined>,
  'createDonation' : ActorMethod<[Donation], undefined>,
  'deactivateMember' : ActorMethod<[string], undefined>,
  'deleteBeneficiary' : ActorMethod<[string], undefined>,
  'getAllBeneficiaries' : ActorMethod<[], Array<Beneficiary>>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllCertificates' : ActorMethod<[], Array<Certificate>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllMemberReferrals' : ActorMethod<[string], Array<Referral>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignById' : ActorMethod<[string], [] | [Campaign]>,
  'getCertificateById' : ActorMethod<[string], [] | [Certificate]>,
  'getDonationById' : ActorMethod<[string], [] | [Donation]>,
  'getDonationsByCampaignId' : ActorMethod<[string], Array<Donation>>,
  'getMemberById' : ActorMethod<[string], [] | [Member]>,
  'getMembersByDesignation' : ActorMethod<[string], Array<Member>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerMember' : ActorMethod<[Member], string>,
  'replyEnquiry' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startCampaign' : ActorMethod<[Campaign], undefined>,
  'submitEnquiry' : ActorMethod<[Enquiry], undefined>,
  'unblockMember' : ActorMethod<[string], undefined>,
  'updateBeneficiary' : ActorMethod<[string, Beneficiary], undefined>,
  'updateCampaign' : ActorMethod<[string, Campaign], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];