/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Beneficiary = IDL.Record({
  'id' : IDL.Text,
  'documents' : IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob }),
  'name' : IDL.Text,
  'helpHistory' : IDL.Vec(IDL.Text),
  'helpType' : IDL.Text,
  'address' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Certificate = IDL.Record({
  'id' : IDL.Text,
  'issueDate' : IDL.Text,
  'templateId' : IDL.Text,
  'recipientName' : IDL.Text,
  'certificateType' : IDL.Text,
  'qrCode' : IDL.Text,
});
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'donorName' : IDL.Text,
  'campaignId' : IDL.Opt(IDL.Text),
  'paymentMode' : IDL.Text,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'goalAmount' : IDL.Nat,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'amountRaised' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Text,
  'replied' : IDL.Bool,
});
export const Referral = IDL.Record({
  'referredId' : IDL.Text,
  'referrerId' : IDL.Text,
  'timestamp' : IDL.Text,
  'successful' : IDL.Bool,
});
export const Birthday = IDL.Record({
  'day' : IDL.Nat8,
  'month' : IDL.Nat8,
  'year' : IDL.Nat16,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'blocked' : IDL.Null,
  'deactivated' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'dob' : Birthday,
  'status' : Status,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'joiningDate' : IDL.Text,
  'email' : IDL.Text,
  'referralId' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
  'photo' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBeneficiary' : IDL.Func([Beneficiary], [], []),
  'addMemberReferral' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockMember' : IDL.Func([IDL.Text], [], []),
  'createCertificate' : IDL.Func([Certificate], [], []),
  'createDonation' : IDL.Func([Donation], [], []),
  'deactivateMember' : IDL.Func([IDL.Text], [], []),
  'deleteBeneficiary' : IDL.Func([IDL.Text], [], []),
  'getAllBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllMemberReferrals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Referral)],
      ['query'],
    ),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaignById' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
  'getCertificateById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'getDonationById' : IDL.Func([IDL.Text], [IDL.Opt(Donation)], ['query']),
  'getDonationsByCampaignId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Donation)],
      ['query'],
    ),
  'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMembersByDesignation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Member)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func([Member], [IDL.Text], []),
  'replyEnquiry' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startCampaign' : IDL.Func([Campaign], [], []),
  'submitEnquiry' : IDL.Func([Enquiry], [], []),
  'unblockMember' : IDL.Func([IDL.Text], [], []),
  'updateBeneficiary' : IDL.Func([IDL.Text, Beneficiary], [], []),
  'updateCampaign' : IDL.Func([IDL.Text, Campaign], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Beneficiary = IDL.Record({
    'id' : IDL.Text,
    'documents' : IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob }),
    'name' : IDL.Text,
    'helpHistory' : IDL.Vec(IDL.Text),
    'helpType' : IDL.Text,
    'address' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Certificate = IDL.Record({
    'id' : IDL.Text,
    'issueDate' : IDL.Text,
    'templateId' : IDL.Text,
    'recipientName' : IDL.Text,
    'certificateType' : IDL.Text,
    'qrCode' : IDL.Text,
  });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'donorName' : IDL.Text,
    'campaignId' : IDL.Opt(IDL.Text),
    'paymentMode' : IDL.Text,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'goalAmount' : IDL.Nat,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'amountRaised' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Text,
    'replied' : IDL.Bool,
  });
  const Referral = IDL.Record({
    'referredId' : IDL.Text,
    'referrerId' : IDL.Text,
    'timestamp' : IDL.Text,
    'successful' : IDL.Bool,
  });
  const Birthday = IDL.Record({
    'day' : IDL.Nat8,
    'month' : IDL.Nat8,
    'year' : IDL.Nat16,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'blocked' : IDL.Null,
    'deactivated' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'dob' : Birthday,
    'status' : Status,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'joiningDate' : IDL.Text,
    'email' : IDL.Text,
    'referralId' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBeneficiary' : IDL.Func([Beneficiary], [], []),
    'addMemberReferral' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockMember' : IDL.Func([IDL.Text], [], []),
    'createCertificate' : IDL.Func([Certificate], [], []),
    'createDonation' : IDL.Func([Donation], [], []),
    'deactivateMember' : IDL.Func([IDL.Text], [], []),
    'deleteBeneficiary' : IDL.Func([IDL.Text], [], []),
    'getAllBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllMemberReferrals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaignById' : IDL.Func([IDL.Text], [IDL.Opt(Campaign)], ['query']),
    'getCertificateById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'getDonationById' : IDL.Func([IDL.Text], [IDL.Opt(Donation)], ['query']),
    'getDonationsByCampaignId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMembersByDesignation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Member)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func([Member], [IDL.Text], []),
    'replyEnquiry' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startCampaign' : IDL.Func([Campaign], [], []),
    'submitEnquiry' : IDL.Func([Enquiry], [], []),
    'unblockMember' : IDL.Func([IDL.Text], [], []),
    'updateBeneficiary' : IDL.Func([IDL.Text, Beneficiary], [], []),
    'updateCampaign' : IDL.Func([IDL.Text, Campaign], [], []),
  });
};

export const init = ({ IDL }) => { return []; };