/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Beneficiary {
    id: string;
    documents: {
        id: string;
        blob: ExternalBlob;
    };
    name: string;
    helpHistory: Array<string>;
    helpType: string;
    address: string;
    contactDetails: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Enquiry {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: string;
    replied: boolean;
}
export interface Donation {
    id: string;
    memberId?: string;
    date: string;
    donorName: string;
    campaignId?: string;
    paymentMode: string;
    amount: bigint;
    receiptNumber: string;
    transactionId: string;
}
export interface Birthday {
    day: number;
    month: number;
    year: number;
}
export interface Campaign {
    id: string;
    status: string;
    title: string;
    goalAmount: bigint;
    endDate: string;
    description: string;
    amountRaised: bigint;
    startDate: string;
}
export interface Referral {
    referredId: string;
    referrerId: string;
    timestamp: string;
    successful: boolean;
}
export interface Member {
    id: string;
    dob: Birthday;
    status: Status;
    name: string;
    designation: string;
    joiningDate: string;
    email: string;
    referralId: string;
    address: string;
    gender: Gender;
    phone: string;
    photo: ExternalBlob;
}
export interface Certificate {
    id: string;
    issueDate: string;
    templateId: string;
    recipientName: string;
    certificateType: string;
    qrCode: string;
}
export interface UserProfile {
    memberId?: string;
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum Status {
    active = "active",
    blocked = "blocked",
    deactivated = "deactivated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBeneficiary(newBeneficiary: Beneficiary): Promise<void>;
    addMemberReferral(referrerId: string, referredId: string, timestamp: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockMember(memberId: string): Promise<void>;
    createCertificate(newCertificate: Certificate): Promise<void>;
    createDonation(newDonation: Donation): Promise<void>;
    deactivateMember(memberId: string): Promise<void>;
    deleteBeneficiary(beneficiaryId: string): Promise<void>;
    getAllBeneficiaries(): Promise<Array<Beneficiary>>;
    getAllCampaigns(): Promise<Array<Campaign>>;
    getAllCertificates(): Promise<Array<Certificate>>;
    getAllDonations(): Promise<Array<Donation>>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllMemberReferrals(memberId: string): Promise<Array<Referral>>;
    getAllMembers(): Promise<Array<Member>>;
    getAllReferrals(): Promise<Array<Referral>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampaignById(campaignId: string): Promise<Campaign | null>;
    getCertificateById(certificateId: string): Promise<Certificate | null>;
    getDonationById(donationId: string): Promise<Donation | null>;
    getDonationsByCampaignId(campaignId: string): Promise<Array<Donation>>;
    getMemberById(memberId: string): Promise<Member | null>;
    getMembersByDesignation(designation: string): Promise<Array<Member>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerMember(newMemberData: Member): Promise<string>;
    replyEnquiry(enquiryId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startCampaign(newCampaign: Campaign): Promise<void>;
    submitEnquiry(newEnquiry: Enquiry): Promise<void>;
    unblockMember(memberId: string): Promise<void>;
    updateBeneficiary(beneficiaryId: string, updatedBeneficiary: Beneficiary): Promise<void>;
    updateCampaign(campaignId: string, updatedCampaign: Campaign): Promise<void>;
}
import type { Beneficiary as _Beneficiary, Birthday as _Birthday, Campaign as _Campaign, Certificate as _Certificate, Donation as _Donation, ExternalBlob as _ExternalBlob, Gender as _Gender, Member as _Member, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBeneficiary(arg0: Beneficiary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBeneficiary(await to_candid_Beneficiary_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBeneficiary(await to_candid_Beneficiary_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMemberReferral(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemberReferral(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemberReferral(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockMember(arg0);
            return result;
        }
    }
    async createCertificate(arg0: Certificate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCertificate(arg0);
            return result;
        }
    }
    async createDonation(arg0: Donation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonation(to_candid_Donation_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonation(to_candid_Donation_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateMember(arg0);
            return result;
        }
    }
    async deleteBeneficiary(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBeneficiary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBeneficiary(arg0);
            return result;
        }
    }
    async getAllBeneficiaries(): Promise<Array<Beneficiary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBeneficiaries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBeneficiaries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCampaigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCampaigns();
            return result;
        }
    }
    async getAllCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCertificates();
            return result;
        }
    }
    async getAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return result;
        }
    }
    async getAllMemberReferrals(arg0: string): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemberReferrals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemberReferrals(arg0);
            return result;
        }
    }
    async getAllMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReferrals(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReferrals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReferrals();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaignById(arg0: string): Promise<Campaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificateById(arg0: string): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificateById(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificateById(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationById(arg0: string): Promise<Donation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationsByCampaignId(arg0: string): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByCampaignId(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByCampaignId(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberById(arg0: string): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembersByDesignation(arg0: string): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersByDesignation(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersByDesignation(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerMember(arg0: Member): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(await to_candid_Member_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(await to_candid_Member_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async replyEnquiry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyEnquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyEnquiry(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startCampaign(arg0: Campaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCampaign(arg0);
            return result;
        }
    }
    async submitEnquiry(arg0: Enquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0);
            return result;
        }
    }
    async unblockMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockMember(arg0);
            return result;
        }
    }
    async updateBeneficiary(arg0: string, arg1: Beneficiary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBeneficiary(arg0, await to_candid_Beneficiary_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBeneficiary(arg0, await to_candid_Beneficiary_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCampaign(arg0: string, arg1: Campaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaign(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_Beneficiary_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Beneficiary): Promise<Beneficiary> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Member_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Promise<Member> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Campaign]): Campaign | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donation]): Donation | null {
    return value.length === 0 ? null : from_candid_Donation_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Promise<Member | null> {
    return value.length === 0 ? null : await from_candid_Member_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documents: {
        id: string;
        blob: _ExternalBlob;
    };
    name: string;
    helpHistory: Array<string>;
    helpType: string;
    address: string;
    contactDetails: string;
}): Promise<{
    id: string;
    documents: {
        id: string;
        blob: ExternalBlob;
    };
    name: string;
    helpHistory: Array<string>;
    helpType: string;
    address: string;
    contactDetails: string;
}> {
    return {
        id: value.id,
        documents: await from_candid_record_n19(_uploadFile, _downloadFile, value.documents),
        name: value.name,
        helpHistory: value.helpHistory,
        helpType: value.helpType,
        address: value.address,
        contactDetails: value.contactDetails
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
}): Promise<{
    id: string;
    blob: ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.blob)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: [] | [string];
    date: string;
    donorName: string;
    campaignId: [] | [string];
    paymentMode: string;
    amount: bigint;
    receiptNumber: string;
    transactionId: string;
}): {
    id: string;
    memberId?: string;
    date: string;
    donorName: string;
    campaignId?: string;
    paymentMode: string;
    amount: bigint;
    receiptNumber: string;
    transactionId: string;
} {
    return {
        id: value.id,
        memberId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.memberId)),
        date: value.date,
        donorName: value.donorName,
        campaignId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.campaignId)),
        paymentMode: value.paymentMode,
        amount: value.amount,
        receiptNumber: value.receiptNumber,
        transactionId: value.transactionId
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: _Birthday;
    status: _Status;
    name: string;
    designation: string;
    joiningDate: string;
    email: string;
    referralId: string;
    address: string;
    gender: _Gender;
    phone: string;
    photo: _ExternalBlob;
}): Promise<{
    id: string;
    dob: Birthday;
    status: Status;
    name: string;
    designation: string;
    joiningDate: string;
    email: string;
    referralId: string;
    address: string;
    gender: Gender;
    phone: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        dob: value.dob,
        status: from_candid_Status_n28(_uploadFile, _downloadFile, value.status),
        name: value.name,
        designation: value.designation,
        joiningDate: value.joiningDate,
        email: value.email,
        referralId: value.referralId,
        address: value.address,
        gender: from_candid_Gender_n30(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        photo: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.photo)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: [] | [string];
    name: string;
    role: string;
}): {
    memberId?: string;
    name: string;
    role: string;
} {
    return {
        memberId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.memberId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    blocked: null;
} | {
    deactivated: null;
}): Status {
    return "active" in value ? Status.active : "blocked" in value ? Status.blocked : "deactivated" in value ? Status.deactivated : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Beneficiary>): Promise<Array<Beneficiary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Beneficiary_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n22(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Promise<Array<Member>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Member_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_Beneficiary_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Beneficiary): Promise<_Beneficiary> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Donation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Donation): _Donation {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_Member_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): Promise<_Member> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob)
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId?: string;
    date: string;
    donorName: string;
    campaignId?: string;
    paymentMode: string;
    amount: bigint;
    receiptNumber: string;
    transactionId: string;
}): {
    id: string;
    memberId: [] | [string];
    date: string;
    donorName: string;
    campaignId: [] | [string];
    paymentMode: string;
    amount: bigint;
    receiptNumber: string;
    transactionId: string;
} {
    return {
        id: value.id,
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        date: value.date,
        donorName: value.donorName,
        campaignId: value.campaignId ? candid_some(value.campaignId) : candid_none(),
        paymentMode: value.paymentMode,
        amount: value.amount,
        receiptNumber: value.receiptNumber,
        transactionId: value.transactionId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: Birthday;
    status: Status;
    name: string;
    designation: string;
    joiningDate: string;
    email: string;
    referralId: string;
    address: string;
    gender: Gender;
    phone: string;
    photo: ExternalBlob;
}): Promise<{
    id: string;
    dob: _Birthday;
    status: _Status;
    name: string;
    designation: string;
    joiningDate: string;
    email: string;
    referralId: string;
    address: string;
    gender: _Gender;
    phone: string;
    photo: _ExternalBlob;
}> {
    return {
        id: value.id,
        dob: value.dob,
        status: to_candid_Status_n43(_uploadFile, _downloadFile, value.status),
        name: value.name,
        designation: value.designation,
        joiningDate: value.joiningDate,
        email: value.email,
        referralId: value.referralId,
        address: value.address,
        gender: to_candid_Gender_n45(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        photo: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photo)
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId?: string;
    name: string;
    role: string;
}): {
    memberId: [] | [string];
    name: string;
    role: string;
} {
    return {
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documents: {
        id: string;
        blob: ExternalBlob;
    };
    name: string;
    helpHistory: Array<string>;
    helpType: string;
    address: string;
    contactDetails: string;
}): Promise<{
    id: string;
    documents: {
        id: string;
        blob: _ExternalBlob;
    };
    name: string;
    helpHistory: Array<string>;
    helpType: string;
    address: string;
    contactDetails: string;
}> {
    return {
        id: value.id,
        documents: await to_candid_record_n10(_uploadFile, _downloadFile, value.documents),
        name: value.name,
        helpHistory: value.helpHistory,
        helpType: value.helpType,
        address: value.address,
        contactDetails: value.contactDetails
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    blocked: null;
} | {
    deactivated: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.blocked ? {
        blocked: null
    } : value == Status.deactivated ? {
        deactivated: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
